name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Transfer all files and folders to server
        env:
          SSH_USER: veramoh1
          SSH_PASSWORD: K2Rq!ZhMUE6yh.!
          SSH_HOST: udine.id.domainesia.com 
          SSH_PORT: 64000
        run: |
          sshpass -p $SSH_PASSWORD scp -P $SSH_PORT -o StrictHostKeyChecking=no -r ./* $SSH_USER@$SSH_HOST:/home/veramoh1/public_html/new-website